package org.mym.ymlib.compiler.util

internal const val COMMENT_GEN_FILE = "This file was generated by Ymlib processor. \n" +
            "Your changes will be lost when sources are regenerated.\n" +
            "Visit https://github.com/Muyangmin/YmLib for more details."